# Generated by Django 4.1 on 2022-10-24 03:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_progress_status_remove_news_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blog_pics/')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('body', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
