# Generated by Django 4.1 on 2022-10-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Gallery'},
        ),
    ]
