# Generated by Django 4.1 on 2022-10-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_gallery_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_title', models.CharField(max_length=255, unique=True)),
                ('ev_img', models.ImageField(blank=True, null=True, upload_to='events_pics/')),
                ('ev_date', models.DateTimeField(blank=True, null=True)),
                ('ev_loc', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ev_category', models.ManyToManyField(related_name='events', to='home.category')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-created_on'],
            },
        ),
    ]
