# Generated by Django 4.1 on 2022-10-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_title', models.CharField(max_length=255, null=True, unique=True)),
                ('fac_img', models.ImageField(blank=True, null=True, upload_to='facilities_pics/')),
                ('fac_state', models.CharField(default='New/Old', max_length=100)),
                ('fac_price', models.IntegerField(null=True)),
                ('fac_availability', models.CharField(default='Available/Not Available', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['-created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='birth_certificate',
            name='parent_identification',
        ),
    ]
