# Generated by Django 4.1 on 2022-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_committee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_title', models.CharField(max_length=255, null=True, unique=True)),
                ('sp_img', models.ImageField(blank=True, null=True, upload_to='sports_pics/')),
                ('sp_desc', models.CharField(max_length=2000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sports and Recreation',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Ward Committee'},
        ),
    ]
