# Generated by Django 4.1 on 2022-10-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_sports_alter_committee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='d_file',
            field=models.FileField(null=True, upload_to='Downloads_Files/'),
        ),
    ]
