# Generated by Django 4.1 on 2022-10-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_downloads_d_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('t_file', models.FileField(null=True, upload_to='Tenders_Files/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tenders and Notices',
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterModelOptions(
            name='downloads',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Downloads & Resources'},
        ),
    ]
